### ISSUE TITLE
2.1.0 datime error

### ISSUE THREAD

**Issue by mr-flibble** [HandyGuySoftware/dupReport#36]
Hello, after upgrade I get this error message (no problem before upgrade)

```
Traceback (most recent call last):
  File "B:\Dulezite_Programy_universal\dupReport_PortablePython3.2.5.1\dupReport.py", line 182, in <module>
    globs.inServer.processMessage(nxtMsg)
  File "B:\Dulezite_Programy_universal\dupReport_PortablePython3.2.5.1\dremail.py", line 338, in processMessage
    dtTimStmp = drdatetime.toTimestamp(xDate, dfmt='YYYY/MM/DD', tfmt='HH:MM:SS')  # Convert the string into a timestamp
  File "B:\Dulezite_Programy_universal\dupReport_PortablePython3.2.5.1\drdatetime.py", line 106, in toTimestamp
    ts = datetime.datetime(year, month, day, hour, minute, second).timestamp()
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'
```

My config:
```
dateformat = DD.MM.YYYY
timeformat = HH:MM:SS
warnoncollect = false
applyutcoffset = false
show24hourtime = true

```

Last messages in log:
```
]
Database.searchForMessage(<DRDILCEFW2U4.C5C3URJ3TJ903@xx>)
Database.execSqlStmt(): Executing SQL command.
Message ID [<DRDILCE4W2U4.C7C3URJ3TJ903@xx>] does not exist. Adding to DB
drDateTime.toTimestamp(2017/11/17 15:54:29, YYYY/MM/DD, HH:MM:SS, None)
```

Probably date and time in problematic email (which worked in 2.0.4) 
`Date: Fri, 17 Nov 2017 15:54:29 +0100`

![image](https://user-images.githubusercontent.com/5197625/33770440-e0396fe2-dc2d-11e7-8841-87fe00d0977b.png)

**Comment by HandyGuySoftware** [comment]
What version of Python are you running?

**Comment by mr-flibble** [comment]
Hello, I use Python 3.2.5.1 on Windows - from this portable package http://portablepython.com/wiki/PortablePython3.2.5.1/ 

But if you think that may cause problem, I can try it to another version

**Comment by HandyGuySoftware** [comment]
I am suspecting that Portable Python does not have the full datetime libraries that regular Python has. dupReport 2.1 uses a more extensive library set than 2.0 did, which is why it requires Python 3 to run. It also appears that Portable Python is no longer under development, which would explain why it is still on Python Version 2. Would it be possible to install a full current Python 3 distribution?

**Comment by mr-flibble** [comment]
Thanks and sorry - from the beginning I was afraid I could use the problem version.

Now I tried it on two Windows PC, one with latest installed Python 3.6.3

And second PC with WinPython 3.4.4.2 (portable python still in development) 


This is error message from Python 3.6.3
```
C:\Users\kratkoruky\Desktop\python>dupReport.py -i
Traceback (most recent call last):
  File "C:\Users\kratkoruky\Desktop\python\dupReport.py", line 182, in <module>
    globs.inServer.processMessage(nxtMsg)
  File "C:\Users\kratkoruky\Desktop\python\dremail.py", line 425, in processMessage
    globs.log.write(3, 'endTimeStamp=[{}] beginTimeStamp=[{}]'.format(drdatetime.fromTimestamp(dateParts['endTimestamp']
datetime.fromTimestamp(dateParts['beginTimestamp'])))
  File "C:\Users\kratkoruky\Desktop\python\drdatetime.py", line 131, in fromTimestamp
    dt = datetime.datetime.fromtimestamp(ts)
TypeError: an integer is required (got type str)
```

And from WinPython
```
PS D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64> .\python.exe D:\dupReport-2.1.0_Beta\dupReport-2.1.0_Beta\dupReport.py
 -i
Traceback (most recent call last):
  File "D:\dupReport-2.1.0_Beta\dupReport-2.1.0_Beta\dupReport.py", line 187, in <module>
    globs.inServer.processMessage(nxtMsg)
  File "D:\dupReport-2.1.0_Beta\dupReport-2.1.0_Beta\dremail.py", line 425, in processMessage
    globs.log.write(3, 'endTimeStamp=[{}] beginTimeStamp=[{}]'.format(drdatetime.fromTimestamp(dateParts['endTimestamp']), drdatetime.fromTimestamp(dateParts['beginTimestamp'])))
  File "D:\dupReport-2.1.0_Beta\dupReport-2.1.0_Beta\drdatetime.py", line 131, in fromTimestamp
    dt = datetime.datetime.fromtimestamp(ts)
TypeError: a float is required
PS D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64>
```

End of WinPython log:
```
]

Warnings: []

Errors: []



, Failed: .*, 0, 1
drdatetime.fromTimestamp(1512214115, DD.MM.YYYY, HH:MM:SS)
```

**Comment by dcurrey** [comment]
Keep runing into the TypeError: a float is required myself.

Should dt = datetime.datetime.fromtimestamp(float(ts))?

**Comment by HandyGuySoftware** [comment]
Yeah, just seeing that now. Not sure why it works here but tripping you guys up. Give me a minute...

**Comment by HandyGuySoftware** [comment]
OK, pushed an update. Also fixed #38 . Give it a try. (Fingers crossed)

**Comment by mr-flibble** [comment]
THANKS ! :-)

It works. 

WinPython nad Python 3.6.3 they no longer have a problem
On the other hand PortablePython3.2.5.1 has still library problem ( https://github.com/HandyGuySoftware/dupReport/issues/36#issue-280513967 ), so he is not compatible with 2.1.0 beta.

I'm switching to WinPython - thanks again.
